FROM eclipse-temurin:21
RUN mkdir /app
WORKDIR /app
COPY gradle/wrapper gradle/wrapper
COPY gradlew .
COPY settings.gradle .
RUN ./gradlew build --no-daemon
COPY . .
EXPOSE 8100

CMD ["java", "-jar", "build/libs/user-0.0.1-SNAPSHOT.jar"]
